application: triv-bot
version: 2
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images
  
- url: /font
  static_dir: static/font

- url: /icons
  static_dir: static/icons

# Cron
- url: /cron/.*
  script: cron.py
  login: admin

# Queue
- url: /queue/.*
  script: queue.py
  login: admin

- url: /test
  script: main.py
  login: admin

- url: /test/.*
  script: main.py
  login: admin

- url: .*
  script: main.py
